# 融合與校準
fusion:
  method: "linear"
  weights:
    cosine: 0.7
    bm25: 0.3
  bias: 0.0
  threshold: 0.5
  scaler: "zscore"   # zscore|none

calibration:
  method: "temperature"
  bins: 15
  report_dir: "kb_local/logs/calib_reports"
  version: "1.0.0"

evaluation:
  metrics: ["pr_auc", "f1@best_t", "ece", "nll", "brier"]
  labels_path: "data/labels.jsonl"

