name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'   # pip 依賴快取由 setup-python 原生支援

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black mypy pytest

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Type check (mypy)
        run: mypy .

      - name: Unit tests
        env:
          PYTHONWARNINGS: default
        run: pytest -q

      - name: Minimal integration smoke
        if: always()
        run: |
          python - <<'PY'
          print("smoke: import core modules")
          import importlib, sys
          for m in ["src", "src.ingest", "src.normalize", "src.link", "src.build_kb"]:
              importlib.import_module(m)
          print("ok")
          PY
